name: synapse
description: "AI-powered spatial brainstorming and knowledge-weaving tool."
# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-156.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For rendering 3D models in the application.
  model_viewer_plus: ^1.7.0

  # ADDED: For generating unique identifiers for each node.
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

