name: synapse
description: "AI-powered spatial brainstorming and knowledge-weaving tool."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The core package for displaying 3D models.
  model_viewer_plus: ^1.7.0

  # The OFFICIAL and REQUIRED web platform implementation for the webview.
  # This is the missing piece.
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

